databases:
  - name: employeemanager_db
    plan: free
    databaseName: employeemanager
    user: employeemanager

services:
  - type: web
    plan: free
    name: employeemanager
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn employeemanager.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: employeemanager_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
